In [1]:
import torch
import numpy as np

In [2]:
# ----------- 创建张量 -------------
# 1 基础创建torch.tensor
"""
    总结：
    掌握/常用的是 torch.tensor
"""
# 1.1- 标量创建张量
# 查看源代码：ctrl+鼠标左键
t1 = torch.tensor(data=999)
t1

NameError: name 'torch' is not defined

In [3]:
# 1.2- numpy中的ndarray数组创建张量
arr1 = np.random.randn(2,3)
t2 = torch.tensor(data=arr1)    # float64：64位的小数
t2

tensor([[ 0.4814, -1.4372,  2.0956],
        [-0.3325,  0.3079,  0.2692]], dtype=torch.float64)

In [4]:
# 1.3- 通过容器创建张量
t3 = torch.tensor([11, 22, 33])
t3

tensor([11, 22, 33])

In [5]:
t4 = torch.tensor([1.99, 2.888, 3.66])
t4

tensor([1.9900, 2.8880, 3.6600])

In [6]:
# 查看张量中元素的数据类型
t4.dtype

torch.float32

In [8]:
# 2 其他创建方式
# 注意：下面的写法是生成包含5个元素的张量。而不是将5变成张量
# t5 = torch.Tensor(5)

t5 = torch.Tensor([5])  # 将5变成张量
t5

tensor([5.])

In [9]:
t5.dtype

torch.float32

In [13]:
# 3 创建指定类型的张量
# t6 = torch.IntTensor([5])
t6 = torch.IntTensor([5.9999])  # 只保留整数位
t6

tensor([5], dtype=torch.int32)

In [16]:
# t7 = torch.DoubleTensor([5.12])
t7 = torch.DoubleTensor([5])
t7

tensor([5.], dtype=torch.float64)

In [17]:
# 4 创建线性张量
# arange生成的范围是[start,end)，左闭右开
# 注意：step表示步长
t8 = torch.arange(start=1,end=6,step=1)
t8

tensor([1, 2, 3, 4, 5])

In [19]:
# linspace生成的范围是[start,end]，左右都是闭区间
# 注意：steps不表示步长，表示要生成多少个元素
# t9 = torch.linspace(start=1,end=6,steps=6)
t9 = torch.linspace(start=1,end=6,steps=10)
t9

tensor([1.0000, 1.5556, 2.1111, 2.6667, 3.2222, 3.7778, 4.3333, 4.8889, 5.4444,
        6.0000])

In [23]:
# 5 随机张量
# 生成区间是[low,high)。左闭右开的区间
# t10 = torch.randint(low=1,high=5,size=(4,))    # 生成包含4个元素的向量张量
t10 = torch.randint(low=1,high=5,size=(2,3,4))    # 生成三维张量
t10

tensor([[[2, 1, 2, 2],
         [4, 1, 1, 4],
         [3, 2, 3, 3]],

        [[1, 3, 2, 1],
         [1, 3, 3, 2],
         [2, 1, 4, 2]]])

In [33]:
# 获得随机数种子
print(torch.initial_seed())

# 手动设置随机数种子
torch.manual_seed(127)
t11 = torch.randint(low=1,high=5,size=(2,3,4))    # 生成三维张量
print(t11)

127
tensor([[[2, 1, 3, 1],
         [1, 4, 2, 4],
         [2, 1, 4, 4]],

        [[4, 2, 2, 4],
         [3, 1, 2, 2],
         [2, 3, 3, 1]]])


In [36]:
t12 = torch.rand(4) # 随机生成指定个数的小数
t12 = torch.rand(size=(2,3,4)) # 随机生成指定形状的小数
t12

tensor([[[0.1111, 0.9318, 0.0182, 0.3809],
         [0.1440, 0.2452, 0.6083, 0.8952],
         [0.6465, 0.7892, 0.5625, 0.8666]],

        [[0.1350, 0.9597, 0.8182, 0.2901],
         [0.3612, 0.0750, 0.7593, 0.6831],
         [0.9402, 0.3005, 0.4093, 0.8498]]])

In [38]:
# 随机生成小数：小数满足标准正态分布（均值为0，方差为1）
t13 = torch.randn(4)
t13 = torch.randn(size=(2,3,4))
t13

tensor([[[ 0.9347, -2.0291,  1.1263,  1.4862],
         [-1.5426,  0.2050,  0.1117,  0.4148],
         [ 1.4210, -0.6128, -0.6794, -1.0068]],

        [[-0.5272, -0.1360,  1.4657, -1.1894],
         [-1.1959,  0.7908, -0.5945, -1.0970],
         [-0.0438,  0.1059,  0.4136, -0.0111]]])

In [39]:
# 6 创建指定值的张量
t14 = torch.randn(size=(2,3,4))
t14

tensor([[[ 1.1442,  0.4688, -0.4365, -0.9550],
         [ 0.5601, -0.8032,  0.4990,  0.2639],
         [ 0.5580,  2.4106,  2.3127,  0.6236]],

        [[ 1.2812,  1.7094,  0.0463,  0.6220],
         [-0.6531, -1.4496, -0.9902,  2.5121],
         [ 0.5915,  0.4670,  0.5213,  0.2319]]])

In [40]:
"""
    1- ones创建指定形状的全1张量
    2- ones_like，仿照某个张量的形状，创建指定形状的全1张量
    3- zeros创建指定形状的全0张量。【掌握】
    4- zeros_like，仿照某个张量的形状，创建指定形状的全0张量
    5- full创建指定形状，并且元素值也是人为指定的张量
    6- full_like，仿照某个张量的形状，并且元素值是人为指定的张量
"""
t15 = torch.ones(size=(3,4))    
t16 = torch.ones_like(t14)
t17 = torch.zeros(size=(3,4))
t18 = torch.zeros_like(t14)
t19 = torch.full(size=(3,4), fill_value=666)
t20 = torch.full_like(t14, fill_value=666)

print(f"ones-->{t15}")
print(f"ones_like-->{t16}")
print(f"zeros-->{t17}")
print(f"zeros_like-->{t18}")
print(f"full-->{t19}")
print(f"full_like-->{t20}")

ones-->tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
ones_like-->tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
zeros-->tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
zeros_like-->tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
full-->tensor([[666, 666, 666, 666],
        [666, 666, 666, 666],
        [666, 666, 666, 666]])
full_like-->tensor([[[666., 666., 666., 666.],
         [666., 666., 666., 666.],
         [666., 666., 666., 666.]],

        [[666., 666., 666., 666.],
         [666., 666., 666., 666.],
         [666., 666., 666., 666.]]])


In [42]:
# 7 张量元素数据类型转换
t_1 = torch.tensor([11, 22, 33])
t_1.dtype

torch.int64

In [44]:
# 通用的写法。掌握
t_2 = t_1.type(dtype=torch.float16) # 推荐的写法
t_2 = t_1.type(dtype=torch.DoubleTensor)
t_2

tensor([11., 22., 33.], dtype=torch.float64)

In [46]:
t_3 = torch.tensor([1.678, 2.543])  # 默认是float32
print(t_3)
print(t_3.dtype)

tensor([1.6780, 2.5430])
torch.float32


In [52]:
t_4 = t_3.half()    # float16
t_4 = t_3.short()    # 短整型int16
t_4 = t_3.int()     # int32
t_4 = t_3.long()    # 长整型int64
print(t_4.dtype)

torch.int64
