In [1]:
import torch
import numpy as np

In [9]:
# 1------------------ 张量转成Numpy ------------------
t1 = torch.tensor([11, 22, 33])
print(t1)

# 默认共享内存
arr1 = t1.numpy()   # ndarray
print(type(arr1))
print(arr1)

# 使用copy，不共享内存。就是一个深拷贝
arr1 = t1.numpy().copy()

t1[1] = 999
print(f"张量：{t1}")
print(f"Numpy：{arr1}")


tensor([11, 22, 33])
<class 'numpy.ndarray'>
[11 22 33]
张量：tensor([ 11, 999,  33])
Numpy：[11 22 33]


In [14]:
# 2------------------ Numpy转成张量 ------------------
arr2 = np.array([11, 22, 33])
print(type(arr2))
print(arr2)

# from_numpy会共享内存
t2 = torch.from_numpy(arr2)
print(t2)

arr2[1] = 999
print(f"Numpy：{arr2}") 
print(f"张量：{t2}")

print("-"*30)

# torch.tensor(Numpy)不会共享内存
arr2 = np.array([11, 22, 33])
t3 = torch.tensor(arr2)
print(t3)

arr2[1] = 666
print(f"Numpy：{arr2}") 
print(f"张量：{t3}")


<class 'numpy.ndarray'>
[11 22 33]
tensor([11, 22, 33])
Numpy：[ 11 999  33]
张量：tensor([ 11, 999,  33])
------------------------------
tensor([11, 22, 33])
Numpy：[ 11 666  33]
张量：tensor([11, 22, 33])


In [15]:
# 3------------------ 标量转成张量 ------------------
t4 = torch.tensor(data=999)
t4


tensor(999)

In [18]:
# 4------------------ 张量转成标量 ------------------
t5 = torch.tensor(data=999)
print(type(t5))

result = t5.item()
print(result)
print(type(result)) # int

# 注意事项：如果张量中有多个元素，那么不允许转成标量。否则会报如下的异常：
# a Tensor with 2 elements cannot be converted to Scalar
t6 = torch.tensor(data=[11, 22])
result_2 = t6.item()
print(result_2)

<class 'torch.Tensor'>
999
<class 'int'>


RuntimeError: a Tensor with 2 elements cannot be converted to Scalar