In [1]:
import torch
import numpy as np

In [8]:
# 设置随机数种子
torch.manual_seed(129)

# 1----------------------- 算术运算 -----------------------
t1 = torch.randint(low=-3,high=5,size=(3,4))    # 创建3行4列的二维张量
t1

tensor([[ 4,  4, -3,  3],
        [-3,  3,  3, -3],
        [-2, -1,  3, -1]])

In [9]:
# 【掌握】+-*/
t2 = t1+10
t3 = t1*10
print(f"加法：{t2}")
print(f"乘法：{t3}")

加法：tensor([[14, 14,  7, 13],
        [ 7, 13, 13,  7],
        [ 8,  9, 13,  9]])
乘法：tensor([[ 40,  40, -30,  30],
        [-30,  30,  30, -30],
        [-20, -10,  30, -10]])


In [12]:
# 函数
t4 = t1.add(20)
t5 = t1.mul(100) # mul->multi乘法
t6 = t1.neg()   # 正数变负数，负数变正数
print(f"加法：{t4}")
print(f"乘法：{t5}")
print(f"取负数：{t6}")
print(t1)

加法：tensor([[24, 24, 17, 23],
        [17, 23, 23, 17],
        [18, 19, 23, 19]])
乘法：tensor([[ 400,  400, -300,  300],
        [-300,  300,  300, -300],
        [-200, -100,  300, -100]])
取负数：tensor([[-4, -4,  3, -3],
        [ 3, -3, -3,  3],
        [ 2,  1, -3,  1]])
tensor([[ 4,  4, -3,  3],
        [-3,  3,  3, -3],
        [-2, -1,  3, -1]])


In [13]:
# 带下划线的函数：原始数据会收到影响
# t1.add_(20)   # 推荐的写法
t7 = t1.add_(20)
print(f"t1-->{t1}")
print(f"t7-->{t7}")

t1-->tensor([[24, 24, 17, 23],
        [17, 23, 23, 17],
        [18, 19, 23, 19]])
t7-->tensor([[24, 24, 17, 23],
        [17, 23, 23, 17],
        [18, 19, 23, 19]])


In [17]:
# 2------------------- 张量点乘 ---------------------
"""
    点乘总结：
        1- 两个张量对应位置的元素进行乘法运算
        2- 注意：两个张量的形状必须完全相同
"""
A = torch.tensor(data=[[1,2], [3,4]])
B = torch.tensor(data=[[5,6], [7,8]])         # 2行2列

# 下面的形状与A的不同，因此会报错
# B = torch.tensor(data=[[5,6], [7,8], [9, 10]])  # 3行2列

result = A*B        # 推荐掌握
# result = A.mul(B)
result

tensor([[ 5, 12],
        [21, 32]])

In [21]:
# 3------------------- 张量的矩阵乘法 ---------------------
"""
    矩阵乘法的总结：
        注意：前一个矩阵的列数与后一个矩阵的行数，必须相同
"""
torch.manual_seed(129)
A = torch.randint(low=1,high=5,size=(2,3))   # 2行3列
B = torch.randint(low=1,high=5,size=(3,4))   # 3行4列

# 下面B的行与A的列不等，因此会报错
# B = torch.randint(low=1,high=5,size=(2,4))   # 2行4列
print(f"A-->{A}")
print(f"B-->{B}")

result_2 = A@B    # 推荐掌握
# result_2 = A.matmul(B)
print(f"结果：{result_2}")

A-->tensor([[4, 4, 1],
        [3, 1, 3]])
B-->tensor([[3, 1, 2, 3],
        [3, 3, 2, 2],
        [2, 2, 2, 2]])
结果：tensor([[26, 18, 18, 22],
        [18, 12, 14, 17]])
