In [1]:
import torch

In [2]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
t1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
# sum求和。【掌握】
s_1 = t1.sum()      # 将张量中所有的元素值进行求和
s_2 = t1.sum(dim=0) # 按照第一个维度进行计算
s_3 = t1.sum(dim=1) # 按照第二个维度进行计算
# s_5 = t1.sum(dim=2) # 按照第三个维度进行计算
s_4 = t1.sum(dim=-1) # 按照最后一个维度进行计算。常用

print(f"s_1-->{s_1}")
print(f"s_2-->{s_2}")
print(f"s_3-->{s_3}")
print(f"s_4-->{s_4}")
# print(f"s_5-->{s_5}")

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [7]:
# 其他计算函数
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [11]:
mean_result = t2.mean() # 算均值=21/6
print(mean_result)

min_result = t2.min()
print(min_result)

sqrt_result = t2.sqrt()
print(sqrt_result)

log2_result = t2.log2()
print(log2_result)

tensor(3.5000)
tensor(1.)
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
tensor([[0.0000, 1.0000, 1.5850],
        [2.0000, 2.3219, 2.5850]])


In [13]:
# sum(dim)作用在三维的张量上
torch.manual_seed(129)
t9 = torch.randint(low=1,high=5,size=(2,3,4))
t9

tensor([[[4, 4, 1, 3],
         [1, 3, 3, 1],
         [2, 3, 3, 3]],

        [[2, 2, 2, 2],
         [2, 2, 1, 2],
         [1, 4, 2, 2]]])

In [14]:
print("-->",t9.sum())
print("0-->",t9.sum(dim=0))
print("1-->",t9.sum(dim=1))
print("2-->",t9.sum(dim=2))
print("-1-->",t9.sum(dim=-1))

--> tensor(55)
0--> tensor([[6, 6, 3, 5],
        [3, 5, 4, 3],
        [3, 7, 5, 5]])
1--> tensor([[ 7, 10,  7,  7],
        [ 5,  8,  5,  6]])
2--> tensor([[12,  8, 11],
        [ 8,  7,  9]])
-1--> tensor([[12,  8, 11],
        [ 8,  7,  9]])
