In [1]:
import torch

In [8]:
t0 = torch.randint(0,10,size=(4,5))
t0

tensor([[5, 4, 1, 2, 9],
        [0, 8, 7, 3, 0],
        [0, 5, 1, 9, 3],
        [7, 9, 8, 4, 2]])

In [11]:
# 【掌握】1----- 简单的行、列索引 --------
# 语法：张量对象[行索引,列索引]
# 获取第一行
print(t0[0])

# 获取第一列
print(t0[:, 0])

print(t0[2, 4])

tensor([5, 4, 1, 2, 9])
tensor([5, 0, 0, 7])
tensor(3)


In [12]:
# 【掌握】2------ 范围索引：与容器中的切片操作完全一样 -------
# 语法：张量对象[行索引开始:行索引结束:步长, 列索引开始:列索引结束:步长]，左闭右开
# 需求1：前3行的前2列数据
print(t0[:3, :2])

tensor([[5, 4],
        [0, 8],
        [0, 5]])


In [13]:
# 需求2：第2行到最后的行，并且前2列的数据
print(t0[1:, :2])

tensor([[0, 8],
        [0, 5],
        [7, 9]])


In [14]:
# 【了解】3------- 列表索引 -----
# 需求1：返回(第0行,第1列)、(1,2)两个位置的元素
print(t0[[0, 1], [1, 2]])

tensor([4, 7])


In [15]:
# 需求2：获取两个元素的坐标是(2,4)、(3,3)
# 语法：张量对象[[行1,行2], [列1,列2]]
print(t0[[2, 3], [4, 3]])

tensor([3, 4])


In [16]:
# 获取4个元素，坐标分别是(2,4)、(2,3)、(3,4)、(3,3)
print(t0[[[2], [3]], [4, 3]])

tensor([[3, 9],
        [2, 4]])


In [19]:
# 【了解】4------- 布尔索引 -------
# 需求1：第3列大于5的，对应的行数据
# 取出第3列
print(t0[:, 3])

# 判断是否是大于5
print(t0[:, 3] > 5)

# 取出对应的行数据
print(t0[t0[:, 3] > 5, :])

tensor([2, 3, 9, 4])
tensor([False, False,  True, False])
tensor([[0, 5, 1, 9, 3]])


In [20]:
# 【了解】5------ 多维索引 --------
t1 = torch.randint(0,10,size=(3,4,5))
t1

tensor([[[2, 0, 0, 4, 4],
         [8, 2, 4, 5, 3],
         [4, 5, 5, 0, 7],
         [3, 5, 6, 6, 9]],

        [[5, 0, 3, 6, 4],
         [6, 1, 1, 7, 2],
         [5, 2, 7, 8, 1],
         [9, 3, 5, 8, 3]],

        [[2, 4, 0, 2, 1],
         [0, 1, 0, 2, 6],
         [2, 8, 0, 1, 2],
         [1, 1, 3, 6, 9]]])

In [21]:
# 获取0轴上的数据
t1[0, :, :]

tensor([[2, 0, 0, 4, 4],
        [8, 2, 4, 5, 3],
        [4, 5, 5, 0, 7],
        [3, 5, 6, 6, 9]])

In [22]:
# 获取1轴上的数据
t1[:, 0, :]

tensor([[2, 0, 0, 4, 4],
        [5, 0, 3, 6, 4],
        [2, 4, 0, 2, 1]])

In [23]:
# 获取2轴上的数据
t1[:, :, 0]

tensor([[2, 8, 4, 3],
        [5, 6, 5, 9],
        [2, 0, 2, 1]])