In [1]:
import torch

In [2]:
t1 = torch.randint(1,10,size=(2,3))
t2 = torch.randint(1,10,size=(2,3))
print(t1)
print(t2)

tensor([[8, 2, 8],
        [1, 9, 4]])
tensor([[5, 8, 1],
        [9, 3, 1]])


In [5]:
# cat/concat
cat_1 = torch.cat(tensors=[t1,t2], dim=0)
print(cat_1)    # 4行3列

cat_2 = torch.cat(tensors=[t1,t2], dim=1)
print(cat_2)    # 2行6列

# 因为上面创建的是二维张量，因此dim的取值最大是1
# cat_3 = torch.cat(tensors=[t1,t2], dim=2)
# print(cat_3)

tensor([[8, 2, 8],
        [1, 9, 4],
        [5, 8, 1],
        [9, 3, 1]])
tensor([[8, 2, 8, 5, 8, 1],
        [1, 9, 4, 9, 3, 1]])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [9]:
# 注意：除了拼接的维度以外，其他维度必须相同
t3 = torch.randint(1,10,size=(2,3))
t4 = torch.randint(1,10,size=(4,3))   # 列数相同，因此正常
# t4 = torch.randint(1,10,size=(2,4))   # 列数不同，因此报错
print(t1)
print(t2)

cat_4 = torch.cat(tensors=[t3,t4], dim=0)
print(cat_4)

tensor([[8, 2, 8],
        [1, 9, 4]])
tensor([[5, 8, 1],
        [9, 3, 1]])
tensor([[1, 4, 8],
        [9, 8, 9],
        [7, 4, 7],
        [8, 6, 2]])


In [12]:
# stack：张量的形状要完全一致
t6 = torch.randint(1,10,size=(5,6))
t7 = torch.randint(1,10,size=(5,6))
# t7 = torch.randint(1,10,size=(5,7))
# t7 = torch.randint(1,10,size=(7,6))
print(t6)
print(t7)
print(torch.stack(tensors=[t6, t7]))

tensor([[8, 4, 1, 7, 5, 1],
        [2, 6, 2, 4, 7, 9],
        [6, 3, 8, 8, 7, 1],
        [3, 1, 4, 7, 8, 6],
        [4, 3, 6, 6, 4, 9]])
tensor([[7, 6, 8, 8, 6, 9],
        [5, 3, 8, 6, 2, 6],
        [7, 1, 1, 3, 7, 2],
        [8, 4, 6, 5, 5, 7],
        [3, 6, 9, 1, 5, 7],
        [2, 3, 7, 7, 8, 2],
        [6, 9, 8, 5, 7, 2]])


RuntimeError: stack expects each tensor to be equal size, but got [5, 6] at entry 0 and [7, 6] at entry 1